version: "2.4"

services:
  api:
    image: api
    build:
      target: dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15.4
    volumes:
      - api-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis:7.0.2
    volumes:
      - api-redis:/data

volumes:
  api-db:
  api-redis:
