version: "2.4"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "${SEVER_PORT:-8080}:8080"
      - 9229:9229
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.4
    volumes:
      - api-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis:7.0.2
    volumes:
      - api-redis:/data

volumes:
  api-db:
  api-redis:
