version: "2.4"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "${SEVER_PORT:-8080}:8080"
      - 9229:9229
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.4
    ports:
      - "3306:5432"
    volumes:
      - api-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.0.2
    volumes:
      - api-redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  api-db:
  api-redis:
