# fly.toml app configuration file generated for aged-sea-1086 on 2023-09-25T12:27:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-sea-1086"
primary_region = "lhr"

[build]
  build-target = "prod"

[deploy]
  release_command = "pnpm run db:migrate"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

