CREATE TABLE
  IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    user_id UUID DEFAULT gen_random_uuid () NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    last_login TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT NOW ()
  );